### ISSUE TITLE
Can't install as dependency on Windows

### ISSUE THREAD

**Issue by endquote** [fent/node-youtube-dl#109]
My project has a dependency on this module. When I install it on Windows, I get an error:

```
C:\tmp>npm install laundry

> youtube-dl@1.11.1 postinstall C:\tmp\node_modules\laundry\node_modules\youtube-dl
> node ./scripts/download.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'generate-object-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\tmp\node_modules\laundry\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\index.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "laundry"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! youtube-dl@1.11.1 postinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-dl@1.11.1 postinstall script 'node ./scripts/download.js'.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs youtube-dl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\tmp\npm-debug.log
```

If I install the module by itself it works ok.

```
C:\tmp>npm install youtube-dl
-
> youtube-dl@1.11.1 postinstall C:\tmp\node_modules\youtube-dl
> node ./scripts/download.js

Downloaded youtube-dl 2016.05.10
youtube-dl@1.11.1 node_modules\youtube-dl
├── mkdirp@0.5.1 (minimist@0.0.8)
├── streamify@0.2.5 (hashish@0.0.4)
└── request@2.72.0 (oauth-sign@0.8.2, aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.3, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, aws4@1.4.1, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, form-data@1.0.0-rc4, combined-stream@1.0.5, mime-types@2.1.11, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)

C:\tmp>
```

Still researching it...

**Comment by endquote** [comment]
If I do this:

```
npm install youtube-dl
npm install laundry
```

It works ok.

If I do this:

```
npm install -g youtube-dl
npm install -g laundry
```

It fails again.

**Comment by endquote** [comment]
I observed this on node v4.4.4, but updating to v6.1.0 seems to have made the problem go away.

Weird.

**Comment by puranjayjain** [comment]
@endquote try it on node v5.xx its a bit more stable and is supported by a lot of packages on npm.
