### ISSUE TITLE
Dump with link with regional restriction    

### ISSUE THREAD

**Issue by pawanvivekananda** [fent/node-youtube-dl#111]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: /home/pawan/pawan/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=18 http://www.youtube.com/watch?v=RnO1usyMyEo
ERROR: YouTube said: This video is available in India only

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by przemyslawpluta** [comment]
Looks similar to https://github.com/rg3/youtube-dl/issues/2853
