### ISSUE TITLE
requires the python youtube-dl?

### ISSUE THREAD

**Issue by tejasmanohar** [fent/node-youtube-dl#58]
does this node module require the python youtube-dl cli to be installed on the user's system?

**Comment by fent** [comment]
No, it downloads the latest one when it's being installed or updated.

**Comment by Nosthertus** [comment]
i have an error for python dependecy

```sh
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn python ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```

i am running on windows 10 with the lastest npm version. as well as the lastest package version
