### ISSUE TITLE
bin/youtube-dl has problem

### ISSUE THREAD

**Issue by phongdaohp** [fent/node-youtube-dl#76]
Hello you,

I see your bin/youtube-dl had problem, please check.

Best regard
Phong Dao

**Comment by fent** [comment]
what problem?

**Comment by phongdaohp** [comment]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Command failed: Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: --max-quality

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

**Comment by Joshua-F** [comment]
Seems to be related to #74.

**Comment by fent** [comment]
`--max-quality` was changed to `--format`
