### ISSUE TITLE
Module is not working

### ISSUE THREAD

**Issue by tjiricek** [fent/node-youtube-dl#79]
Started tests and it didn't pass.

> vows ./test/*.js --spec

  ♢ download

  a video with format specified
    ✗ data returned
      Error: spawn ENOENT
      at errnoException (child_process.js:1000:11)
      at Process.ChildProcess._handle.onexit (child_process.js:791:34)
    ✗ file was downloaded
      Error: spawn ENOENT
      at errnoException (child_process.js:1000:11)
      at Process.ChildProcess._handle.onexit (child_process.js:791:34)
  a video with no format specified
    ✗ data returned
      Error: spawn ENOENT
      at errnoException (child_process.js:1000:11)
      at Process.ChildProcess._handle.onexit (child_process.js:791:34)
    ✗ file was downloaded
      Error: spawn ENOENT
      at errnoException (child_process.js:1000:11)
      at Process.ChildProcess._handle.onexit (child_process.js:791:34)
  a video with subtitles
    ✗ subtitles were downloaded
      Error: spawn ENOENT
      at errnoException (child_process.js:1000:11)
      at Process.ChildProcess._handle.onexit (child_process.js:791:34)

  ♢ getExtractors

**Comment by tjiricek** [comment]
Sorry, my bad. There is no information or warning about youtube-dl and python dependencies. You should log this info to console when somebody tries to run the script.
