### ISSUE TITLE
I can stream to client using express js?

### ISSUE THREAD

**Issue by matheuschimelli** [fent/node-youtube-dl#89]
I can stream to client using express js?

**Comment by fent** [comment]
The returned object is a readable stream, so yes it can be piped to the response.

**Comment by matheuschimelli** [comment]
I am using the first example, but express returns a error:
`Error: Cannot pipe. Not readable.
   at WriteStream.Writable.pipe (_stream_writable.js:154:22)
   at /home/ubuntu/workspace/download-openmusic/index.js:43:49
   at Layer.handle [as handle_request] (/home/ubuntu/workspace/download-openmusic/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/ubuntu/workspace/download-openmusic/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/ubuntu/workspace/download-openmusic/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/home/ubuntu/workspace/download-openmusic/node_modules/express/lib/router/layer.js:95:5)
   at /home/ubuntu/workspace/download-openmusic/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/home/ubuntu/workspace/download-openmusic/node_modules/express/lib/router/index.js:330:12)
   at next (/home/ubuntu/workspace/download-openmusic/node_modules/express/lib/router/index.js:271:10)
   at SendStream.error (/home/ubuntu/workspace/download-openmusic/node_modules/express/node_modules/serve-static/index.js:120:7)`

And this is my code:
`app.get('/download',function(req,res){
  
var video = youtubedl('http://www.youtube.com/watch?v=bM7SZ5SBzyY',
  // Optional arguments passed to youtube-dl.
  ['--format=18'],
  // Additional options can be given for calling `child_process.execFile()`.
  { cwd: __dirname });

// Will be called when the download starts.
video.on('info', function(info) {
  console.log('Download started');
  console.log('filename: ' + info.filename);
  console.log('size: ' + info.size);
});

video.pipe(fs.createWriteStream('myvideo.mp4')).pipe(res);

})`

**Comment by przemyslawpluta** [comment]
@matheuschimelli which version of `express` do you use?

**Comment by matheuschimelli** [comment]
`4.13.3`

**Comment by przemyslawpluta** [comment]
@matheuschimelli wou can't pipe a readable stream to another readable stream. Just change to:

```js
video.pipe(res);
```
