### ISSUE TITLE
Can't install as part of a global package

### ISSUE THREAD

**Issue by endquote** [fent/node-youtube-dl#93]
I published a new library which depends on youtube-dl, but it can't be installed under recent versions of node.
https://www.npmjs.com/package/laundry

```
Obelus:Source josh$ sudo npm install -g laundry
Password:
npm WARN lifecycle youtube-dl@1.10.5~preinstall: cannot run in wd %s %s (wd=%s) youtube-dl@1.10.5 node ./scripts/download.js /usr/local/lib/node_modules/.staging/youtube-dl-d7cb69a6
/usr/local/lib
└── (empty)
```

I tried switching the package to pull from this repo directly rather than npm, and get a different error:

```
Obelus:laundry josh$ sudo npm install -g laundry
/usr/local/bin/laundry -> /usr/local/lib/node_modules/laundry/index.js

> youtube-dl@1.11.0 postinstall /usr/local/lib/node_modules/laundry/node_modules/youtube-dl
> node ./scripts/download.js

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at addToPkg (/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/lib/downloader.js:48:6)
    at error (/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/lib/downloader.js:82:7)
    at Request.end (/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/lib/downloader.js:30:43)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/laundry/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
/usr/local/lib
└── (empty)
```

I can install the package locally (`npm install youtube-dl`, or `npm install laundry`) just fine, but as a dependency of a globally-installed package, it fails.

This is on OS X 10.11.3, node 5.6.0, npm 3.6.0.

Not sure why this is an issue, as you can see I am running under `sudo`, but I reproduced the problem on two machines.

**Comment by endquote** [comment]
The PR n #92 seems to solve it.

**Comment by endquote** [comment]
Well, it solves the installer problem, but then when I try to actually use ytdl in my program, I get:

`ERROR: youtube-dl file in . does not exist.`

**Comment by endquote** [comment]
Also this:

```
Obelus:laundry josh$ sudo npm update --save

> youtube-dl@1.11.0 postinstall /Users/josh/Source/laundry/node_modules/youtube-dl
> node ./scripts/download.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1182
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1182:25)
    at startup (node.js:98:32)
    at node.js:933:3
```

**Comment by przemyslawpluta** [comment]
@endquote will have a look. Are you installing directly from master branch or from npm?

**Comment by endquote** [comment]
Thanks! The first set of output in the original post on this thread is from npm, the other two are pulling right from master.

**Comment by przemyslawpluta** [comment]
@endquote try latest git master. I've moved the bin directory location into data directory and not into package.json bin

**Comment by endquote** [comment]
Still no luck. Here is the output of `sudo npm install -g laundry`

Looks like you're trying to use `/Users/josh/Library/Application Support`, which is a Windows thing.

```
> youtube-dl@1.11.0 postinstall /usr/local/lib/node_modules/laundry/node_modules/youtube-dl
> node ./scripts/download.js

/usr/local/lib/node_modules/laundry/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/Users/josh/Library/Application Support/youtube-dl'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/usr/local/lib/node_modules/laundry/node_modules/mkdirp/index.js:71:13)
    at createBase (/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/lib/downloader.js:40:10)
    at downloader (/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/lib/downloader.js:57:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/scripts/download.js:3:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "laundry"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! youtube-dl@1.11.0 postinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@1.11.0 postinstall script 'node ./scripts/download.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs youtube-dl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/josh/Source/npm-debug.log
npm ERR! code 1
Obelus:Source josh$ 
```

**Comment by przemyslawpluta** [comment]
@endquote this looks like permission issues on your side

```bash
Error: EACCES: permission denied, mkdir '/Users/josh/Library/Application Support/youtube-dl'
```

It's using [path-extra](https://www.npmjs.com/package/path-extra) to get `datadir` do you expect different directory for data?

**Comment by endquote** [comment]
I'm not sure what the correct directory is, but it's clear that npm isn't supposed to be writing there. I tried on another machine and got the same result, this time just installing yt-dl and not my package.

```
RGBTV:~ tv$ sudo npm install -g https://github.com/fent/node-youtube-dl.git
Password:

> youtube-dl@1.11.0 postinstall /usr/local/lib/node_modules/youtube-dl
> node ./scripts/download.js

/usr/local/lib/node_modules/youtube-dl/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/Users/tv/Library/Application Support/youtube-dl'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Function.sync (/usr/local/lib/node_modules/youtube-dl/node_modules/mkdirp/index.js:71:13)
    at createBase (/usr/local/lib/node_modules/youtube-dl/lib/downloader.js:40:10)
    at downloader (/usr/local/lib/node_modules/youtube-dl/lib/downloader.js:57:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/youtube-dl/scripts/download.js:3:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

Why does it need to be in a specific path? Shouldn't it just be in a `bin/` directory relative to the module location?

**Comment by przemyslawpluta** [comment]
That was the original behaviour new option has been added to facilitate ability to place `bin` into a different location https://github.com/fent/node-youtube-dl/issues/88 and not default local `bin` directory.

Works on OS I've tested on but clearly this is causing issues on your side.

**Comment by endquote** [comment]
Using `pathEx.datadir` does seem like a sensible way to go... but for some reason it just doesn't work when installing globally via npm on Mac. Made a PR to use a local directory instead. This seems to work for me, but I haven't tested on other platforms yet.

**Comment by endquote** [comment]
Seems to work on latest Windows 10 as well.

**Comment by przemyslawpluta** [comment]
@endquote thanks for https://github.com/fent/node-youtube-dl/pull/95 I've dropped `pathEx.datadir` in favour of keeping all the details internally. You can still specify external bin but now all the details about the location will be kept in internal bin.

Give it a go ...

**Comment by endquote** [comment]
I think this is getting closer. This is what I have after installing my package:

```
Obelus:youtube-dl josh$ pwd
/usr/local/lib/node_modules/laundry/node_modules/youtube-dl
Obelus:youtube-dl josh$ ls -al
total 64
drwxr-xr-x   11 nobody  staff   374B Mar 12 18:29 ./
drwxr-xr-x  163 root    staff   5.4K Mar 12 18:29 ../
-rw-r--r--    1 nobody  staff    71B Mar 12 18:28 .npmignore
-rw-r--r--    1 nobody  staff   192B Mar 12 18:28 .travis.yml
-rw-r--r--    1 nobody  staff   1.0K Mar 12 18:28 LICENSE
-rw-r--r--    1 nobody  staff   7.8K Mar 12 18:28 README.md
drwxr--r--    4 nobody  staff   136B Mar 12 18:29 bin/
drwxr-xr-x    8 nobody  staff   272B Mar 12 18:29 example/
drwxr-xr-x    5 nobody  staff   170B Mar 12 18:29 lib/
-rw-r--r--    1 root    staff    11K Mar 12 18:29 package.json
drwxr-xr-x    3 nobody  staff   102B Mar 12 18:28 scripts/
Obelus:youtube-dl josh$ cat bin/details
cat: bin/details: Permission denied
Obelus:youtube-dl josh$ sudo cat bin/details
Password:
{"version":"2016.03.06","path":"/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/bin/youtube-dl"}
```

As a normal user, I can't read the bin directory, which means when the module tries to read the details file, it fails. If I change the permissions of `bin` to be the same as the other subfolders, I can read everything ok.

```
Obelus:youtube-dl josh$ sudo chmod 755 bin
Obelus:youtube-dl josh$ ls -al
total 64
drwxr-xr-x   11 nobody  staff   374B Mar 12 18:29 ./
drwxr-xr-x  163 root    staff   5.4K Mar 12 18:29 ../
-rw-r--r--    1 nobody  staff    71B Mar 12 18:28 .npmignore
-rw-r--r--    1 nobody  staff   192B Mar 12 18:28 .travis.yml
-rw-r--r--    1 nobody  staff   1.0K Mar 12 18:28 LICENSE
-rw-r--r--    1 nobody  staff   7.8K Mar 12 18:28 README.md
drwxr-xr-x    4 nobody  staff   136B Mar 12 18:29 bin/
drwxr-xr-x    8 nobody  staff   272B Mar 12 18:29 example/
drwxr-xr-x    5 nobody  staff   170B Mar 12 18:29 lib/
-rw-r--r--    1 root    staff    11K Mar 12 18:29 package.json
drwxr-xr-x    3 nobody  staff   102B Mar 12 18:28 scripts/
Obelus:youtube-dl josh$ cat bin/details
{"version":"2016.03.06","path":"/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/bin/youtube-dl"}
```

Now everything seems to work fine.

Seems like we just need to change `484` to `755` in the downloader script.

**Comment by przemyslawpluta** [comment]
@endquote this should do it. @EragonJ would be good if you'd test it as well.

**Comment by endquote** [comment]
The `bin` directory still doesn't have the correct permissions.

```
Obelus:Downloads josh$ npm install https://github.com/fent/node-youtube-dl.git

> youtube-dl@1.11.0 postinstall /Users/josh/Downloads/node_modules/youtube-dl
> node ./scripts/download.js

Downloaded youtube-dl 2016.03.14
/Users/josh/Downloads
└─┬ youtube-dl@1.11.0  (git+https://github.com/fent/node-youtube-dl.git#d2a32694f9a8ff31cbd98fb53c0b47e63ca9a51d)

[...stuff...]

Obelus:Downloads josh$ cd node_modules/youtube-dl/
Obelus:youtube-dl josh$ ls -al
total 64
drwxr-xr-x  11 josh  staff   374B Mar 14 14:34 ./
drwxr-xr-x  78 josh  staff   2.6K Mar 14 14:34 ../
-rw-r--r--   1 josh  staff    71B Mar 14 14:34 .npmignore
-rw-r--r--   1 josh  staff   192B Mar 14 14:34 .travis.yml
-rw-r--r--   1 josh  staff   1.0K Mar 14 14:34 LICENSE
-rw-r--r--   1 josh  staff   7.8K Mar 14 14:34 README.md
d-wxr----x   4 josh  staff   136B Mar 14 14:34 bin/
drwxr-xr-x   9 josh  staff   306B Mar 14 14:34 example/
drwxr-xr-x   5 josh  staff   170B Mar 14 14:34 lib/
-rw-r--r--   1 josh  staff    11K Mar 14 14:34 package.json
drwxr-xr-x   3 josh  staff   102B Mar 14 14:34 scripts/
Obelus:youtube-dl josh$ ls bin/
ls: : Permission denied
Obelus:youtube-dl josh$ sudo ls bin/
details		youtube-dl
```

**Comment by przemyslawpluta** [comment]
@endquote try latest master

**Comment by endquote** [comment]
The permissions on the `bin` directory look good, but I get a different error when I try to actually use it in a program.
```
warn:  Error: Command failed: /usr/local/lib/node_modules/laundry/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=ie2yJSCogKY
python: can't open file '/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/bin/youtube-dl': [Errno 13] Permission denied

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
```

If I run this from a command-line I get the same issue:

```
Obelus:~ josh$ /usr/local/lib/node_modules/laundry/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=ie2yJSCogKY
python: can't open file '/usr/local/lib/node_modules/laundry/node_modules/youtube-dl/bin/youtube-dl': [Errno 13] Permission denied
```

If I run it with `sudo` it works.

```
Obelus:~ josh$ ls -al /usr/local/lib/node_modules/laundry/node_modules/youtube-dl/bin/
total 2240
drwxr-xr-x   4 nobody  staff   136B Mar 14 15:10 ./
drwxr-xr-x  11 nobody  staff   374B Mar 14 15:10 ../
-rw-r--r--   1 nobody  staff   108B Mar 14 15:10 details
-rwx--x--x   1 nobody  staff   1.1M Mar 14 15:10 youtube-dl*
```

**Comment by endquote** [comment]
Tested this again -- it looks like if I install my package without sudo, the permissions are set such that I can run it. Another user on the system wouldn't be able to, but that's probably fine.
