### ISSUE TITLE
ERROR: unable to locate youtube-dl details in

### ISSUE THREAD

**Issue by vikmeup** [fent/node-youtube-dl#98]
Can't build it on heroku - v1.11.0 version. Related to permissions

ERROR: unable to locate youtube-dl details in /tmp/build_cae19459a70227cbc28692e5fc17dbe6/vikmeup-MinNodeExpress-127efed7f713a1c21eecc88b513e2df99aa395dd/node_modules/youtube-dl/bin

**Comment by vikmeup** [comment]
@fent Anything on this?

**Comment by przemyslawpluta** [comment]
@vikmeup can you provide entire output during installation

**Comment by vikmeup** [comment]
That's the most I can get, it's related to the last commit with permissions.

**Comment by przemyslawpluta** [comment]
@vikmeup well it looks like it's not permissions ...

Once deployed and during source build installation path is pointing to `/tmp/build_f7aee58993d7588e89d11e25033fb42b/node_modules/youtube-dl/` but at run time it's `/app/node_modules/youtube-dl/` hence inability to locate `bin`.

We might need a special behaviour for `heroku`.

**Comment by przemyslawpluta** [comment]
@vikmeup try latest master it should work fine on `heroku` now

**Comment by vikmeup** [comment]
@przemyslawpluta works fine now! Thanks for fixing it. 

Please push a new release :)

**Comment by martyychang** [comment]
I also had the same problem. For what it's worth, the error reported with `babel-node` and Node.js 6.9.1 is different and hard to decipher. Pasting below in case others are searching for the same error message.

```txt
ubuntu@ip-172-31-16-178:~/Workspace/example-dot-com$ make test
babel-node test.js
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.<anonymous> (/home/ubuntu/Workspace/example-dot-com/node_modules/youtube-dl/lib/youtube-dl.js:19:71)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ubuntu/.yarn-config/global/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/Workspace/example-dot-com/src/Video.js:19:1)
    at Module._compile (module.js:570:32)
    at loader (/home/ubuntu/.yarn-config/global/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ubuntu/.yarn-config/global/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
Makefile:23: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by Dovahkiin-Warrior** [comment]
same issue
![image](https://cloud.githubusercontent.com/assets/16886014/20550958/10da0d88-b109-11e6-8189-05ad9857db8e.png)

**Comment by mayeaux** [comment]
I'm getting the same error :\

**Comment by PsychicCat** [comment]
same???

**Comment by mayeaux** [comment]
I came up with a hacky solution that's working for me
Install youtube-dl as a buildpack and then point your binary towards that on Heroku

**Comment by PsychicCat** [comment]
Not on heroku here. But I tracked down the issue to the downloader.js. There is a postinstall script that requests this page http://rg3.github.io/youtube-dl/download.html then does some regex matching to get the current binary download url. For some reason the html that comes back from request is all corrupted and the regex doesn't match anything, so the binary isn't downloaded. I can't reproduce this in a local environment, only experiencing it on AWS ec2 with node 6.11.1.

**Comment by mayeaux** [comment]
Nice find, I have a feeling it's something to do with Ubuntu vs OS X. Are you using OS X locally?

**Comment by jjg77** [comment]
How did you fix this error?
